"""adding relationship between image and label

Revision ID: cd77a0e20a19
Revises: 
Create Date: 2018-05-26 03:30:36.439644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd77a0e20a19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_association',
    sa.Column('labeling_session', sa.TEXT(), nullable=True),
    sa.Column('labeled_image', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['labeled_image'], ['label.id'], ),
    sa.ForeignKeyConstraint(['labeling_session'], ['labeling_session.id'], )
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###
