"""baseline

Revision ID: 911d0c388567
Revises: 
Create Date: 2018-05-26 16:53:05.093543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '911d0c388567'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('label_names', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labeling_session',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('label_association',
    sa.Column('labeling_session_id', sa.TEXT(), nullable=True),
    sa.Column('label_id', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.ForeignKeyConstraint(['labeling_session_id'], ['labeling_session.id'], )
    )
    op.create_table('labeled_image',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('label', sa.INTEGER(), nullable=True),
    sa.Column('image_id', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labeled_image')
    op.drop_table('label_association')
    op.drop_table('labeling_session')
    op.drop_table('label')
    # ### end Alembic commands ###
